### ISSUE TITLE
Why version Bundler with ASDF?

### ISSUE THREAD

**Issue by nomasprime** [jonathanmorley/asdf-bundler#2]
Hi, just trying to understand the premise of this plugin.

Why would I use this instead of `bundle _version_ …`? I'm guessing it would be so I can specify the version in `.tool-versions` and call without `_version_`, ie, portability?

**Comment by jonathanmorley** [comment]
Bundler only ships with ruby in ruby versions >= 2.6 (https://stdgems.org/compare/). This plugin is most useful alongside versions of ruby < 2.6, so that you can go straight from `asdf install` to `bundle install`
